### ISSUE TITLE
Rendering Lab issue

### ISSUE THREAD

**Issue by MaxenceLecoq921** [adaltas/ece-webtech-2023-fall#3]
Hello Sir, @sergkudinov 

I've observed that in the "Rendering" assignment, you've asked us to implement a `getStaticProps` function. I've also noted that this function is intended for use with `articles.js` located in the "pages" folder. However, this suggests that we're using the Next.js "PAGES" routing. Yet, we're currently utilizing the "APP" routing. Therefore, employing `getStaticProps` doesn't seem suitable for our setup.

Should we restructure the project to use the "PAGES" routing, or is there an alternative to `getStaticProps` that's suitable for "APP" routing?

Best regards.

**Comment by sergkudinov** [comment]
It is up to you, you can stay with App router but implement this differently.

Check out this on [this page](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration):

> Data fetching functions like getServerSideProps and getStaticProps have been replaced with [a new API](https://nextjs.org/docs/app/building-your-application/data-fetching) inside app. getStaticPaths has been replaced with [generateStaticParams](https://nextjs.org/docs/app/api-reference/functions/generate-static-params).

**Comment by MaxenceLecoq921** [comment]
Thank you for your help.
