### ISSUE TITLE
probleme with vercel deployment

### ISSUE THREAD

**Issue by AnthoSun** [adaltas/ece-webtech-2023-fall#6]
I have some problems about deployment, I can't resolve it
![image](https://github.com/adaltas/ece-webtech-2023-fall/assets/119040929/adf79765-268c-43c0-8f4b-9df1f91a329a)
![image](https://github.com/adaltas/ece-webtech-2023-fall/assets/119040929/2502d0df-4ad5-4e54-b7d6-5482f16face8)
is it related to the logs ? if Yes, I don't know how resolve it too : 
![image](https://github.com/adaltas/ece-webtech-2023-fall/assets/119040929/1f6edf2a-f199-475a-8e75-c2159b16c53e)

**Comment by sergkudinov** [comment]
It is probably related to your supabase git submodule, remove it and properly initialize supabase following this guide like I did - https://supabase.com/docs/guides/cli/local-development

<img width="1283" alt="image" src="https://github.com/adaltas/ece-webtech-2023-fall/assets/23199590/36755c42-7e9e-4994-8119-b3e19e3655a3">

**Comment by sergkudinov** [comment]
You still have .gitsubmodule file, as well as some random files not at their place.
You have the corrections where everything is working.

**Comment by AnthoSun** [comment]
I used the template add .env for SUPABASE_AUTH_GITHUB_CLIENT_ID, SUPABASE_AUTH_GITHUB_SECRET and same in the app for NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY with online supabase so in my config.toml, I have : :redirect_uri = "https://mrbklqchxskkoinfwwhs.supabase.co/auth/v1/callback". ALso, my npm run build, run start, run dev, all worked but I still have the same issue when I re-deploy. Thank you for your attention !
![image](https://github.com/adaltas/ece-webtech-2023-fall/assets/119040929/d4db9cb1-699c-49a2-8d2d-d62e516d9d7b)
![image](https://github.com/adaltas/ece-webtech-2023-fall/assets/119040929/cbd2f41e-5f80-4f8f-ad6f-f48f47a98ec1)

**Comment by AnthoSun** [comment]
It was indeed the configuration of NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in Vercel and changing the site URL in Supabase. I think everything is working properly.  Thank you very much.
